### PR TITLE
Refresh keybundle

### PR DESCRIPTION
**Pull request by jschlyter**
- set and honor If-Modified-Since on remote requests
- re-read files automatically if changed (files checked every `cache_time` seconds)

### CODE REVIEW

**Comment by rohe** [comment]
Hmm, have to work on the code coverage.

**Comment by jschlyter** [comment]
https://pypi.org/project/requests-mock/ is your friend

**Comment by jschlyter** [comment]
I'll fix better coverage...

**Comment by rohe** [comment]
Thanks !

**Pull request merged**
