### PR TITLE
Add option ignore_invalid_keys to KeyBundle

### LINKED ISSUE #63: KeyBundle's do_keys ignores invalid keys
KeyBundle's do_keys method tries to load keys from a JSON jwks file and if it finds a key that is considered invalid, it overwrites it in the existing file.

Not sure if this is considered a bug, but it seems counter-intuitive to me. Maybe we should instead raise an exception and let the user/app know that there's an error with their key?

### PR DESCRIPTION
**Pull request by jschlyter**
- If set to True (default), silently ignore invalid keys.
- If set to False, raise exception when processing keys.

closes #63

### CODE REVIEW

**Comment by jschlyter** [comment]
ping @rohe @angelakis

**Review by rohe — APPROVED** [review]
Not really happy with the name but not going to fight getting it changed.

**Comment by jschlyter** [comment]
> Not really happy with the name but not going to fight getting it changed.

If @angelakis has better naming proposal, I'm all for it.

**Comment by jschlyter** [comment]
ping @angelakis

**Comment by jschlyter** [comment]
Timeout from @angelakis, will ask @janste63 review before merging.

**Review by janste63 — APPROVED** [review]

**Pull request merged**
