### PR TITLE
isort everything

### PR DESCRIPTION
**Pull request by jschlyter**
Use isort on all code (and be strict about it). Next step may be to use black (if I dare to propose that…)

### CODE REVIEW

**Comment by rohe** [comment]
Unfortunately the sort function in pycharm does not sort the same way isort does. At least that is my experience.
That creates problems for me. I have to research if one can configure isort to do it the same way.

**Comment by jschlyter** [comment]
Seems to be a way to ask pycharm to work with isort instead of against it, https://github.com/timothycrosley/isort/issues/258

**Comment by rohe** [comment]
Yeah, saw that. Have to look at it closely.

**Comment by rohe** [comment]
Looks like I can set it up to work for cryptojwt but then it will not work for oidcmsg or any other project I'm working on.
Adding isort as an external tool seems to be a general tool setting not per project which is what I'd like to have.

**Pull request merged**
